# ArgumentException

This example demonstrates how to throw and catch an ArgumentException.

## Output

```
10 divided by 2 is 5
7 is not divided by 2 integrally.
```
